### ISSUE TITLE
JSON fields naming convention

### ISSUE THREAD

**Issue by Sylux6** [AzurAPI/azurapi-js-setup#2]
Follow camelCase convention

**Comment by kumo-yun** [comment]
I prefer using-this

**Comment by Sylux6** [comment]
I see, this is `kebab-case` (this naming convention is not very commong and mostly used for URLs)
That being said, there is no naming convention for JSON but programing languages follow one when it comes to generate/parse JSON:

- **Python** - `snake_case`
- **PHP** - `snake_case`
- **Java** - `camelCase`
- **JavaScript** - `camelCase`

**Comment by kumo-yun** [comment]
Yes, I think I should follow camelCase.

**Comment by kumo-yun** [comment]
All the fixes are on the new branch.
Will merge when the wrapper team is ready
