### ISSUE TITLE
HullType Error

### ISSUE THREAD

**Issue by Gaylone** [AzurAPI/azurapi-js-setup#37]
the  hullType of Kashino is wrong,
she should be  a Munition Ship，not a Destroyer.
![}1RZ){15T5K LA){RUCL~NV](https://user-images.githubusercontent.com/69965504/129450675-926880c6-69c0-42c0-b919-94d6df7f512a.png)

**Comment by jasperchua99** [comment]
i suggest u can raise it up on discord, we have the whole team looking into it

**Comment by octo-kumo** [comment]
forgot to close but is fixed
